############################################
#
# Crypty 1.0
# - Best cryptocurrency plugin!
#
#
#
############################################

# Message, HEX SUPPORT
messages:
  transaction:
    receive:
      - ""
      - ""
      - ""
    send:
      - ""
      - ""
      - ""
  wallet:
    buy:
      - ""
      - ""
      - ""
    sell:
      - ""
      - ""
      - ""
    info:
      - ""
      - ""
      - ""
      - ""
    help:
      - ""
      - ""
      - ""
      - ""
    delete:
      - ""
      - ""
      - ""
      - ""
    creation:
      - ""
      - ""
      - ""
      - ""
    price:
      - ""
      - ""
      - ""
      - ""
    close:
      - ""
      - ""
      - ""
      - ""
    open:
      - ""
      - ""
      - ""
      - ""